bin/index.js
readme.md

feat: use existing API dev server

---

src/cli/commands/start.ts
src/runtimeHost.spec.ts
src/utils.ts

Fixes some issues that prevented #41 from working on my machine/setup.
I have a create-react-app app running, listening to localhost:3000. However, `isPortAvailable()` was still returning `true`. 😕 Changed the code to test using a TCP connection instead.
Fixed some tests that were failing because they depended on the name of the folder. They no longer work after the repo was renamed.

Fix startup validation and tests

---

readme.md
src/cli/commands/start.ts
src/cli/config.ts
src/proxy.ts
src/utils.test.ts
src/utils.ts

* Fix `concurrently` resolving to the wrong path (fixes #73)
* Don't default api folder to `api` (fixes #74)
* Use the correct port when running CLI with app or api URIs (fixes #75)
* Fix WebSocket forwarding to dev server (fixes #76)

Fix startup issues and WebSocket forwarding

---

readme.md

- Clarify auth emulation port
- General text clean up

docs: Update README

---

package.json

Add `prepare` script to automatically build the project on local install and linking.
It allows running a dev version and working on the project more easily:
- you can npm install directly from the github repo without errors
- you can clone the project and run `npm link` immediately without errors
As a bonus, this also builds the project before packing or publishing the project, avoiding the possibility of outdated builds when publishing.

build: add npm prepare script

---

src/cli/index.ts

Add the executable bit to the CLI "bin" to avoid permission denied errors when running SWA (ie`zsh: permission denied: swa`).
Note that the change doesn't appear on GitHub.
I had to made a change to the file so the commit gets accepted by the linter rules 😉

fix: update CLI bin file permissions

---

src/cli/commands/start.ts

Core tools are no longer installed using NPM according to official doc.
Using `npx` will result in an error then, this PR will start the `func` tool directly instead to avoid errors.

fix: remove npx to start func command

---

src/cli/commands/start.ts
src/cli/index.ts
src/config.ts
src/core/utils.test.ts
src/core/utils.ts
src/proxy/server.ts
src/swa.d.ts

ref: https://github.com/Azure/static-web-apps-cli/issues/4
Some Web API requires contents served over https (for example: Navigator.mediaDevices.getUserMedia).
Since it can be used if it is provided from a specific location such as localhost and file protocol, we can use by using localhost over http, which is currently available.
So it's a low priority because there are alternatives ways, but I guess this feature will bring it closer to production.
I tried the following command
```
$ pwd
~/Projects/github.com/yamachu/static-web-apps-cli
$ SWA_CLI_APP_USE_HTTPS=true SWA_CLI_APP_SSL_KEY="./scripts/localhost.key" SWA_CLI_APP_SSL_CERT="./scripts/localhost.crt" npm start start http://localhost:8000
```

feat: Support serving web and api over https locally

---

src/cli/commands/start.ts
src/cli/index.ts
src/config.ts
src/proxy/server.ts
src/swa.d.ts

feat: set staticwebapp.config.json location w/ flag

---

src/proxy/server.ts

Still hitting some situations where Ctrl-C doesn't shut down. Looks like something blocks the event loop and the `setTimeout` doesn't get called. Calling `process.exit()` immediately to get around this for now.

fix: exit on Ctrl-C

---

src/cli/commands/start.ts

In the current version, CORS are not enabled properly on the function emulator. Without quotes, the `*` will be expanded which is not really the intent here.
Tested the fix locally with a Svelte project, it fixes the issue.

fix: cors not working

---

.github/workflows/e2e.yml
cypress.json
cypress/fixtures/static/staticwebapp.config.json
cypress/integration/authentication.js
cypress/integration/route-rules-engine.js
src/auth/routes/auth_login_provider.ts
src/public/auth.html

Inject meta tags into page to maintain path and query string in case of rewrite.
Fixes #165

fix: preserve auth provider and post login url on rewrites

---

package-lock.json
src/cli/commands/start.ts
src/proxy/server.ts

Move wait for port logic into the proxy.
* Running `swa start http://localhost:3000 --run "npm:start" --app-location frontend` now works properly
* Moving the wait for API to just before starting the proxy means most of the function app output now prints before the proxy starts. This ensures that this message will no longer be hidden by the function app output:
```
[swa] Available on:
[swa]     http://192.168.187.166:4280
[swa]     http://0.0.0.0:4280
[swa] 
[swa] Azure Static Web Apps emulator started. Press CTRL+C to exit.
```

fix: move port validation and waiting logic into proxy server

---

src/cli/commands/start.ts

Change the error message in case if only one of the options '--ssl-cert' or '--ssl-key' is specified because the SSL feature requires both of the options.

fix: SSL option error message

---

src/auth/routes/auth_logout.spec.ts
src/auth/routes/auth_logout.ts
src/auth/routes/auth_logout_https.spec.ts

Currently, a request to `/.auth/logout` always is redirect to `http://`.
https://github.com/Azure/static-web-apps-cli/blob/db13f3a2646759b5b917733e4eb895674539b345/src/auth/routes/auth_logout.ts#L14
Because this causes a redirection to an invalid URL when `swa` is started with `--ssl` flag, this PR switches the protocol of URL by the value of `process.env.SWA_CLI_APP_SSL`.

fix: redirect to the url which starts with `https://` when logged out if `swa` is started with `--ssl` flag

---

src/auth/routes/auth_logout.spec.ts
src/auth/routes/auth_logout.ts

This PR makes a redirection URL for logging out based on `X-Forwarded-Host` and `X-Forwarded-Proto`.
Currently, the host in the redirection URL for logging out depends on only the `Host` header and the protocol depends on only env `SWA_CLI_APP_SSL`.
Background:
It is confirmed that the redirection URL is always `http://localhost` when SWA-CLI works in a Dev Container on GitHub Codespaces.
I think this is because of the existence of the proxy and `X-Forwarded-` headers can be used for building the appropriate redirection URL.

feat: handle `x-forwarded-host/proto` headers on logging out

---

readme.md
src/cli/index.ts
src/core/utils/cli.spec.ts
src/core/utils/cli.ts

Resolves #147 
Support passing arbitrary commands to `--run`, such as:
* `swa start http://localhost:5000 --run "dotnet watch run"`
* `swa start http://localhost:5000 --run "cd MyApp && dotnet watch run"`

feat: allow --run to take any command

---

package-lock.json
src/public/auth.html

If anonymous or authenticated are not entered by the user, they are not always included when evaluating routes or in APIs. Making a change so that the cookie always includes them.

fix: always include anonymous & authenticated roles

---

src/cli/commands/start.ts

fix: Print CLI version when running --verbose=silly

---

package.json
src/cli/commands/start.ts
src/cli/index.ts
src/config.ts
src/core/constants.ts
src/core/utils/cli.spec.ts
src/core/utils/cli.ts
src/core/utils/net.ts
src/msha/server.ts
src/swa.d.ts

Resolves #253 
Allows user to configure wait timeout before dev server starts using the flag `--devserver-timeout`, such as:
`swa start --devserver-timeout 10000`

feat: Configure await timeout before connecting to a dev server

---

readme.md

I had trouble using the CLI through Angular dev server until I understood that I still need to use the SWA CLI port.

docs: clarify use with dev server

---

src/msha/server.ts

The preview message was a bit loud. Removed color and border. Also relocated it so that the emulator port is the last thing that is printed by the CLI.

fix: change location and display of preview warning

---

readme.md
src/cli/commands/start.ts
src/cli/index.ts
src/swa.d.ts

👋
Fixes #289 
Added the `--func-args` option that allows passing additional arguments to the func start command.
I verified that this will enable scenarios like attaching a debugger to the func host.
I verified that this enabled attaching the VS Code debugger to the func host when I used the following command:
`swa start http://localhost:3000/ --app-location=frontend --run "npm run start" --api api --func-args="--javascript --language-worker -- \"--inspect=9229\""`

feat: Add option to pass arguments to func start command

---

src/core/utils/net.ts

Wait on the API to come up by just connecting over TCP rather than making HTTP requests.
Closes Waiting for API to be ready fails intermittently #275

fix(core): wait on API using tcp

---

cypress/fixtures/static/swa-cli.config.json
package.json
readme.md
schema/swa-cli.config.schema.json
src/cli/index.ts
src/core/utils/cli-config.spec.ts
src/core/utils/cli-config.ts
src/core/utils/logger.ts
src/swa.d.ts

This feature works as described by @anthonychu in https://github.com/Azure/static-web-apps-cli/issues/20#issuecomment-809577522.
* If only one configuration present in config file, running `swa start` will use this configuration.
* Otherwise you must use `swa start <config name>` to use a configuration. If `<config name>` is not found in the config file, no config will be used.
* Added the `--config` option, which allows the user to specify a specific path to a config file to use.
* Added the `--print-config` options, which prints the picked up configuration. Useful for user debugging.
I've updated the readme to document how to use a config file.
One thing to note: this feature can only either take options from the command line or the config file. It cannot merge or mix options. If a …

feat: Add support for swa-cli.config.json file

---

package.json
readme.md
src/cli/index.ts

As suggested in [this comment](https://github.com/Azure/static-web-apps-cli/pull/294#discussion_r711582369)
I think I changed them all, but please check if there are any references to the shorthand options still.
Note: this is a breaking change

feat: Remove shorthand options

---

src/msha/routes-engine/route-processor.ts

I was running into an issue with this while setting up a Vite frontend (React template) with the SWA cli.
The change of adding `matchingRewriteRouteQueryString` to the end results in this:
```
[swa] /src/logo.svgimport=
```
Notice the missing `?` prefix.
I instead replaced it with this:
```diff
if (doesMatchingRewriteRouteHaveQueryStringParameters) {
-    matchingRewriteRoutePath = sanitizedUrl.pathname + matchingRewriteRouteQueryString; // => /src/logo.svgimport=
+    matchingRewriteRoutePath = sanitizedUrl.pathname + sanitizedUrl.search;  // => /src/logo.svg?import
core_1.logger.silly(` - query: ${chalk_1.default.yellow(matchingRewriteRouteQueryString)}`);
}
```
The mapping is now correct.
```
[swa] /src/logo.svg?import
```
And it correctly appends the search params and lets the Vite …

Use sanitizedUrl.search to format search params

---

package-lock.json
package.json
src/cli/commands/start.ts

Fix proposal for #353 
If `func` binary is not found in $path, it will show this message:
It would be possible to interactively propose the user to run the command for him, but currently it's just a copy/paste away and allows users to use their favorite package manager if it's not NPM.
The docs link may also help in case the core tools install with NPM is not working for whatever reason, but also to give more context.

feat: check for func binary and suggest core tools install (#353)

---

src/msha/handlers/function.handler.ts
src/public/auth.html
src/swa.d.ts

SWA documentation describes the client principal data retrievable by applications and
includes reference to claims returned by a custom authentication provider.
Change auth.html to capture mock claims information and store in the StaticWebAppsAuthCookie.
Change function.handler.ts to explicitly remove claims from the client principal data
encoded in the x-ms-client-principal header passed to proxied functions, matching current
SWA runtime behaviour.

feat(auth): include claims in client principal data retrieved via direct-access endpoint

---

src/core/constants.ts

Fixes the CLI to allow external URLS in the `--api-location` parameter.
This fixes #251

fix: Allow --api-location to contact external hostnames

---

package-lock.json
package.json
src/cli/commands/start.ts
src/cli/index.ts
src/config.ts
src/core/constants.ts
src/msha/server.ts
src/swa.d.ts

Note that the default behavior remains unchanged.
Adding `--open` will automatically open the SWA server in the default browser.

feat: add --open option (closes #357)

---

cypress/fixtures/blazor-starter/swa-cli.config.json
cypress/fixtures/static/.github/workflows/azure-static-web-apps-NON-CONFORM.yml
cypress/fixtures/static/swa-cli.config.json
src/cli/commands/start.ts
src/core/utils/workflow-config.ts
src/msha/middlewares/request.middleware.ts
src/msha/routes-engine/rules/headers.ts
src/msha/routes-engine/rules/mime-types.ts
src/msha/routes-engine/rules/navigation-fallback.ts
src/msha/routes-engine/rules/response-overrides.ts
src/public/auth.html

Closes #363 
We scan for GitHub Action workflow files (if present) in order to extract the build configuration. The way we validate the workflow file is based on the default templates that SWA generates when creating a new project. 
Initially, we threw an exception if the workflow file is not valid. With the new fix, we now simply show a warning and keep going.

fix: ignore invalid workflow files

---

.npmignore
package.json

This PR does 2 things:
- It removes the unneeded "pretest" script for building, as jest compiles TS files itself (faster test loop)
- It excludes spec files and pngs from the final package, reducing its download size by 283% (!)
Before:
After:

chore: exclude unneeded files from package

---

schema/swa-cli.config.schema.json
src/cli/commands/deploy.ts
src/cli/commands/login.ts
src/cli/index.ts
src/config.ts
src/swa.d.ts

Cleaned unused settings and constants from schema:
- appArtifactLocation
- build (superseded by appBuildCommand and apiBuildCommand)
- apiPrefix
- swaConfigFilename
- swaConfigFilenameLegacy
- customUrlScheme
- overridableErrorCode
We can't enforce proper schema exclusion for extra properties as we need to migrate to draft/2019-09 to be able to use `unevaluatedProperties` for that. But draft/2019-09 version isn't currently properly supported by VS Code, so it's not the good time to migrate.
I specifically enforced exclusion of `deploymentToken` from config file though.

chore(cli): update json schema (closes #422)

---

docs/ENV.md
src/cli/commands/deploy.ts
src/cli/commands/init.ts
src/cli/commands/login.ts
src/cli/index.ts
src/config.ts
src/core/account.ts
src/core/env.ts
src/core/prompts.ts
src/core/utils/cli-config.ts
src/core/utils/logger.ts
src/core/utils/net.ts
src/swa.d.ts

Supported scenarios when deploying:

feat(deploy): handle different case scenarios 

---

src/cli/commands/deploy.ts

#477 
Adds a fleshed out error message for a missing `apiRuntime` setting to include info on where to create the file and a link to the docs.

Enhance error message for missing staticwebapp.config.json

---

docs/www/docs/cli/swa-build.md
docs/www/docs/cli/swa-config.md
docs/www/docs/cli/swa-deploy.md
docs/www/docs/cli/swa-login.md
docs/www/docs/cli/swa-start.md
docs/www/docs/cli/swa.md
docs/www/docs/intro.md
docs/www/docs/use/1-install.md
docs/www/docs/use/2-emulator.md
readme.md

Links redirecting to "login", "init", "start", "deploy" from Readme are not working

docs: modified links in the readme file.

---

docs/www/docs/cli/swa-config.md

This used to be `context` section (prior to v1.0.0).
https://raw.githubusercontent.com/Azure/static-web-apps-cli/main/schema/swa-cli.config.schema.json
```json
"appLocation": {
"description": "The folder containing the source code of the front-end application",
"type": "string"
},
"outputLocation": {
"description": "The folder containing the built source of the front-end application",
"type": "string"
},
"apiLocation": {
"description": "The folder containing the source code of the API application",
"type": "string"
},
"appDevserverUrl": {
"description": "Connect to the dev server at this URL instead of using output location",
"type": "string"
},
"apiDevserverUrl": {
"description": "Connect to the api server at this URL instead of using api location",
"type": "string"
},
```

Use appDevserverUrl for URL configuration

---

docs/www/docs/cli/swa-init.md

fix typo multiples -> multiple

docs: fix typo in swa-init page

---

docs/www/docs/cli/swa-start.md

The default CLI for Vue.js has been changed to [create-vue](https://github.com/vuejs/create-vue).   
The port has also been changed to `3000`.

update Vue command

---

src/core/utils/net.spec.ts
src/core/utils/net.ts

Ensure the correct default port is parsed from http and https URLs.
Before this change, URLs used to identify remote API servers might be parsed as using port 0. swa-cli would then attempt to make a TCP connection to port 0 and would eventually timeout.
With this change, ports for remote API servers are now correctly identified and connections are made to the server without the timeout occuring.
Relates to #523

fix(core): identify correct default port for http and https urls

---

package-lock.json
src/core/frameworks/frameworks.ts

Pull Request related with #553 
I made some screenshots to show that it is working now. To reproduce, follow the steps below:
1 - Create any Next.Js project. Eg
```bash
npx create-next-app --example hello-world hello-world-app
```
2 - Now run the command 
```bash
swa init
```
After to execute the command it will generate a file **swa-cli.config** with the configuration
```json
{
"$schema": "https://aka.ms/azure/static-web-apps-cli/schema",
"configurations": {
"hello-world-app-glau": {
"appLocation": ".",
"outputLocation": ".next",
"appBuildCommand": "npm run build",
"run": "npm run dev",
"appDevserverUrl": "http://localhost:3000"
}
}
}
```
4 - Now execute the command
```bash
swa start
```
And open a browser on port **localhost:4280**. If you see the message: 'Hello World' it is because …

fix(command:init): dev command for Next.Js projects

---

src/msha/routes-engine/rules/response-overrides.spec.ts
src/msha/routes-engine/rules/response-overrides.ts
src/public/auth.html

Tested locally. This fixes the problem described in #542

fix(cli): enable documented .referrer redirect behavior

---

src/cli/commands/deploy.spec.ts
src/cli/commands/deploy.ts

Static Web Apps is unable to detect SwaCLI as a deployment provider with version included.

Updating deployment provider

---

src/core/func-core-tools.spec.ts
src/core/func-core-tools.ts

With the recent release of support for Node 18 in the Functions v4 runtime, we should update the tools check code to allow that.

fix(api): Node18 support

---

docs/www/docs/contribute/99-troubleshooting.md

Add [comment #576](https://github.com/Azure/static-web-apps-cli/issues/576#issuecomment-1263273587)to troubleshooting.

docs: update troubleshooting with explainer #576

---

docs/www/docs/cli/swa-config.md
docs/www/docs/cli/swa-deploy.md
docs/www/docs/cli/swa-login.md
src/cli/commands/deploy.spec.ts
src/cli/commands/deploy.ts
src/cli/commands/login.ts
src/config.ts
src/core/account.ts
src/core/utils/options.spec.ts
src/swa.d.ts

fix(deploy): create SWA in user-provided Resource Group

---

docs/www/docs/cli/swa-deploy.md
docs/www/docs/cli/swa-login.md
src/cli/commands/login.ts
src/core/utils/options.spec.ts

fix(login): fixed short-form of --clear-credentials flag

---

src/core/account.ts

Cannot redeployed a staticSite when initially created using SwaCli.

fix: handle new provider name when deploying

---

docs/www/docs/contribute/99-troubleshooting.md

docs: Add firewall section to troubleshoot

---

src/cli/commands/start.ts

fix(start): FuncBinary path with space in user home directories

---

src/cli/commands/login.ts

#627 ended up not being enough: it fixed the auth part, but a new error occured when checking the token:
Not sure how I missed it the first time, maybe the token was cached during my initial tests so I missed it.
This PR use the default scope instead of "profile", which will work with all auth methods including clientId/clientSecret.

fix: token scope used when using cliendId/clientSecret auth (fix #541)

---

docs/www/docs/cli/swa-start.md
src/cli/commands/start.ts
src/core/utils/net.spec.ts
src/core/utils/net.ts
src/msha/server.ts

creating separate http and https agents depending on whether:
The user is hitting an http:// or https:// dev server.
The user is starting the CLI using --ssl or --no-ssl (by default)
Also, warning the user if:
They started the CLI using  --ssl but they are connecting to http:// dev server
They started the CLI with no SSL but they are connecting to https:// dev server

fix: providing separate agents for HTTP and HTTPS proxy servers

---

src/cli/commands/init/init.spec.ts
src/cli/commands/init/init.ts
src/swa.d.ts

Current when running `swa init` you cannot override the "apiDevserverUrl" option, which is useful when your backend isn't using provided functions, but for example using a Container App (which maps locally to using a container).
This PR adds the missing prompt for this option along with a unit test.

fix(init): allow to override apiDevserverUrl

---

package-lock.json
package.json
src/cli/commands/login/login.ts
src/core/telemetry/baseTelemetryReporter.ts
src/core/telemetry/baseTelemetrySender.ts
src/core/telemetry/telemetryReporter.ts
src/core/telemetry/telemetryReporterTypes.d.ts
src/core/telemetry/utils.ts

Used AppInisghts for javascript SDK and added a basic telemetry reporter class which is used to send event and error data to an AppInisghts instance. When this reporter is called it lazy loads the appinsights client and sends data as a batch to appinisghts instance. Until the client is loaded event and exception data are stored in queues. Collection of required telemetry data from CLI code will be taken care of in next PR.

feat: telemetry collection basic changes

---

src/cli/commands/index.ts
src/cli/commands/telemetry/index.ts
src/cli/commands/telemetry/register.ts
src/cli/commands/telemetry/telemetry.spec.ts
src/cli/commands/telemetry/telemetry.ts
src/cli/index.ts
src/core/constants.ts
src/core/telemetry/utils.ts
src/core/utils/file.ts
src/swa.d.ts

Added commands to disable/enable telemetry capturing. Command would look like `swa telemetry --disable/enable`.
Also added an environment variable `SWA_DISABLE_TELEMETRY` where users can set the value to true/false.
Users can check the status of telemetry capturing using the command `swa telemetry --status`.
Only one of these flags can be used at a time.

feat(telemetry): added new flags and env variable for opting out

---

.github/workflows/azuresdkdrop.yml
src/core/utils/net.ts
src/msha/handlers/function.handler.ts

Fix: issue [#663](https://github.com/Azure/static-web-apps-cli/issues/663).
Use 127.0.0.1 and [::1] for waitOn() and fetch() when using "swa start src --api-location api" with the default --host=localhost. Then check if any of them successes. This is because localhost may not be resolved to ipv4 on some systems.

fix: waitOn and fetch IPv4&v6 instead of localhost

---

src/core/utils/net.ts
src/msha/middlewares/request.middleware.ts

Fix the swa start command when swa-cli serves from dev servers, including Angular, Blazor, React, and Vue. Now localhost:4280 can reach the dev servers no matter if they are running on ipv4 or ipv6. (Ref: [issue #663](https://github.com/Azure/static-web-apps-cli/issues/663))

fix: support dev server on node 18

---

e2e/detect.spec.js
e2e/samples/db/static-mssql/.gitignore
e2e/samples/db/static-mssql/.vscode/extensions.json
e2e/samples/db/static-mssql/.vscode/launch.json
e2e/samples/db/static-mssql/.vscode/settings.json
e2e/samples/db/static-mssql/.vscode/tasks.json
e2e/samples/db/static-mssql/package.json
e2e/samples/db/static-mssql/readme.md
e2e/samples/db/static-mssql/src/index.html
e2e/samples/db/static-mssql/swa-db-connections/staticwebapp.database.config.json
src/cli/commands/init/init.ts
src/core/frameworks/detect.spec.ts
src/core/frameworks/detect.ts
src/core/frameworks/types.d.ts

This PR supports 'swa init' to ideally detect the data-api-location folder, which contains staticwebapp.database.config.json, and to add it to the swa-cli.config.json file.

feat: support '--data-api-location' in 'swa init'

---

src/msha/handlers/function.handler.ts

This PR fixs [ISSUE #733](https://github.com/Azure/static-web-apps-cli/issues/733). If an api dev server are used, and the apiDevserverUrl can be fetched, swa-cli will accept it even if the response is not ok, for example 404 not found.

fix: accept apiDevserverUrl with non-ok response

---

src/cli/commands/start/start.ts

Changed "stoped" to "stopped" in a log error
Credit @camper0008 for spotting this.
["Stop" and "Stopped", Merriam Webster Dictionary](https://www.merriam-webster.com/dictionary/stop)

fix(cli): fix typo in start command

---

package-lock.json
package.json

Reverts Azure/static-web-apps-cli#747 due to GitHub Codespaces Prebuilds. npm Has been updated to 10.1.0, which hasn't supported node 16 any more.

Revert "chore: prep-release 1.1.5"

---

src/msha/middlewares/request.middleware.ts

The previous wait-on function has a param: initial delay = 1000, which caused the waiting time of a request to a dev server to at least 1000ms. This PR remove the param, which will be 0 by default.

fix: remove initial delay to speed up requests

---

.github/workflows/ci.yml

CI fails in unit tests in the job "test: use node >= 18.x". This is because the step "actions/setup-node@v1" will install node 20 with npm 10, which is unsupported by swa-cli. This PR modified '>=18.x' in the node-version of matirx to 18.x.

ci: change node-version from '>=18.x' to 18.x

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

fix: update node to 18 in dockerfile

---

docs/www/docusaurus.config.js

Right now, Light theme is applied even users OS / Browser preference is dark.
Pullrequest is to apply Light / Dark theme by default based on OS / Browser preference
docusaurus documentation:
https://docusaurus.io/docs/api/themes/configuration#color-mode---dark-mode
[Screencast from 03-10-23 07_12_07 PM IST.webm](https://github.com/Azure/static-web-apps-cli/assets/9389944/7d3fce99-d182-4c36-8b19-6ce7d4e94e5f)

Light / Dark theme applied by default based on OS / Browser preference

---

src/core/utils/user-config.ts

Throw error for [ISSUE #754](https://github.com/Azure/static-web-apps-cli/issues/754) Will add the fallback schema file in the future.

fix: throw error when fail to load SWAConfigSchema

---

src/cli/commands/deploy/deploy.ts
src/core/constants.ts
src/core/deploy-client.ts
src/core/utils/user-config.ts

Refact the [PR #746](https://github.com/Azure/static-web-apps-cli/pull/746). This PR assigned a working dir "staticsites-cli" to run StaticSiteClient.exe when using "swa deploy". The dir will be created and removed automatically under the path of repo. In the deployment process, app and api folders will be copied to this working dir before zipping and uploading. This will fix the bug of https://github.com/Azure/static-web-apps-cli/issues/531, https://github.com/Azure/static-web-apps-cli/issues/550, and support next.js deployment.

feat: add client working dir to support deploying next.js

---

schema/staticwebapp.config.json
src/core/constants.ts
src/core/utils/user-config.ts

Added a logic to load static-web-apps-cli/schema/staticwebapp.config.json as a backup to solve issue #754 and #802

fix: load staticwebapp.config.json schema locally when timeout

---

schema/staticwebapp.config.json
src/core/constants.ts

Supported dotnet-isolated 8.0 for managed APIs by:
- Updated staticwebapp.config.json schema to support dotnet-isolated:8.0 in "platform" for swa start and deploy. Will also Updated the version on [https://json.schemastore.org/staticwebapp.config.json](https://json.schemastore.org/staticwebapp.config.json).
- Supported choosing API version: dotnet-isolated:8.0 for swa init.

feat: support dotnet-isolated 8.0 for managed APIs

---

.github/workflows/labeler.yml

Changed the actions/labeler version from main to v4, since v5 has been released and has some break changes.

ci: set the actions/labeler version to v4

---

src/core/account.ts
src/core/prompts.ts

Currently, when you create a new site via "swa deploy", the CLI always creates a "Free" sku site, but this PR introduces a sku picker that defaults to Free, but allows SKU selection during site creation. This is especially helpful to those who have hit the 5 free site limit and want to create a new site.

fix: Allow SKU selection when creating a new site on "swa deploy"

---

src/core/constants.ts
src/core/utils/auth.ts
src/core/utils/cookie.ts
src/msha/auth/index.ts
src/msha/auth/routes/auth-login-provider-callback.ts
src/msha/auth/routes/auth-login-provider-custom.ts
src/msha/auth/routes/auth-login-provider.ts
src/msha/auth/routes/auth-logout-https.spec.ts
src/msha/auth/routes/auth-logout.spec.ts
src/msha/auth/routes/auth-logout.ts
src/msha/handlers/auth.handler.ts
src/swa.d.ts

The user must first create the necessary GitHub OAuth app and/or Google OAuth Client ID with the redirect URIs set to http://localhost:4280/.auth/login/github and http://localhost:4280/.auth/login/google respectively.
They must then add the "auth" configuration in their staticwebapp.config.json file and set the appropriate environment variables containing client ID and client secret values before running starting the SWA CLI.
User clicks on "Log in with GitHub" link (http://localhost:4280/.auth/login/github), which redirects to https://github.com/login/oauth/authorize.
User logs into GitHub if not already logged in.
User authorizes GitHub OAuth app if not already authorized for their account.
User is redirected back to the static web app.
User clicks on "Log in with Google" link …

feat(auth): Add custom auth support for Google and GitHub providers

---

src/core/func-core-tools.ts

Resolves issue found while testing Node 20 & .NET 8 SWA deployments stating that Node 20 is not supported with Azure Functions Core Tools v4 which is not true 😄 
Docs: https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=javascript%2Cwindows%2Cazure-cli&pivots=nodejs-model-v4 
✖ Found Azure Functions Core Tools v4 which is incompatible with your current Node.js v20.8.1.
✖ See https://aka.ms/functions-node-versions for more information.

Fix target core tool version detection when using Node 20

---

.github/workflows/azuresdkdrop.yml

Removing duplicate step from old workflow file that will cause the OIDC Azure login to fail due to new Federation standards

Remove duplicate azure/login@v1 step in azuresdkdrop workflow

---

.github/workflows/azuresdkdrop.yml

The azuresdkdrop action was throwing this error due to an unknown environment variable:
```
ERROR: argument --account-name: expected one argument
Examples from AI knowledge base:
az storage blob upload --account-name mystorageaccount --account-key 0000-0000 --container-name mycontainer --file /path/to/file --name myblob
Upload a file to a storage blob. (autogenerated)
```
Fixing this error by hardcoding the `azuresdkpartnerdrops` account name used by all Azure SDK partner release drop pipelines

Update azuresdkdrop workflow account-name

---

src/core/frameworks/frameworks.ts
src/core/utils/cli.ts

Commit contains fix to properly set the Vuepress start, build, and dist output properly when initializing the swa-cli.config.json file. Also contains fix where the Vuepress start command was not properly initialized when running "swa start" due to a colon being in the run command.
Fixes #849

fix(cli): Fix VuePress swa init and start

---

readme.md

The current "main visible" install method is the one not recommended. Seen a couple of projects rely on global installs because people just go with that first/visible option.

docs: Make the recommended install the main one

---

src/core/account.ts

The current static-web-apps-deploy task does not support Service Principal, so we always need to use tokens for deployment, but it is very time consuming to configure everything when deploying to multiple SWAs.
If the SWA CLI supports Azure CLI login (azure/login action), deployment would be very simple.
Close #751

feat: Support Azure CLI credential

---

schema/swa-cli.config.schema.json

subscription -> subscriptionId

Fix typo in config schema

---

src/cli/commands/login/login.ts
src/core/constants.ts
src/core/utils/file.ts
src/swa.d.ts

Fixes #859. 
Added an additional check in `swa login` command to check if `~\.azure\azureProfile.json` exists. If it exists, we can parse the currently selected subscriptionId and tenantId to pass into the `swa login` command to prevent another unnecessary selection in the picker.

fix (#859): Add check for azureProfile.json to prevent double login

---

src/cli/commands/start/start.ts

After the most recent PR, "swa start" is still working but the output message with the emulator port 4280 link stop appearing. However it still works if I manually navigate to http://localhost:4280/.
Current main branch:
After fix:

[Fix] Show "swa start" output in console

---

.github/CODEOWNERS

This replaces the codeowners with the current maintainers list.

Replace codeowners with current maintainers list

---

src/core/func-core-tools.spec.ts
src/core/func-core-tools.ts

This PR includes the fixes in #786 and fixes the failing unit test.
Original PR: https://github.com/Azure/static-web-apps-cli/pull/786
Updating the supported node versions to match the [current list](https://learn.microsoft.com/en-gb/azure/azure-functions/functions-reference-node?tabs=javascript%2Cwindows%2Cazure-cli&pivots=nodejs-model-v4#supported-versions), including previews.
Fixes https://github.com/Azure/static-web-apps-cli/issues/756

Refreshing Node.js supported versions

---

schema/staticwebapp.config.json
src/msha/auth/index.ts

Fixes #873: Update MSHA's authentication import statement to include the `.js` file extension when importing the proper authentication route.
Fixes #864: Update the configschema to include Node 20 so using `"platform": {"apiRuntime": "node:20"}` in the staticwebapp.config.json no longer causes an error when starting the emulator.

fix (#873, #864): Start crash including auth & Node 20 support

---

src/cli/commands/deploy/deploy.spec.ts
src/cli/commands/deploy/deploy.ts
src/cli/commands/start/start.ts
src/cli/index.spec.ts
src/cli/index.ts
src/core/utils/json.spec.ts
src/core/utils/json.ts
src/core/utils/update-notifier.ts

(#871) fix: import JSON files using createRequire

---

package.json
src/core/constants.ts
src/msha/auth/index.ts
src/msha/auth/routes/auth-login-provider-callback.ts
src/msha/auth/routes/auth-login-provider-custom.ts
src/swa.d.ts

New feature: Adding AAD custom auth support using the previously created code for Google and GitHub. The previous code has been refactored and generalized for future auth providers to be added as well. Google and Github auth has also been regression tested successfully.
Tested in private environment with custom AAD application using the following staticwebapp.config.json:
Successful /.auth/me call with AAD credentials:
Successful /.auth/me call with Github credentials:
Successful /.auth/me call with Google credentials:

[Feature] Add AAD Custom Auth Support & Setup Custom Auth Framework

---

package-lock.json
package.json
src/core/constants.ts
src/msha/auth/index.ts
src/msha/auth/routes/auth-login-provider-callback.ts
src/msha/auth/routes/auth-login-provider-custom.ts
src/swa.d.ts

New feature: Adding Facebook custom auth support using Facebook's manual OIDC token flow. A few more refactors had to be done to the previous code since Facebook's flow is a little bit different, mainly: 
* Facebook's auth provider schema is different in staticwebapp.config.json
* There is no introspection endpoint after getting the token so we need to manually decode the returned JWT
staticwebapp.config.json:
Facebook /.auth/me:
Github /.auth/me:
AAD /.auth/me:
Google /.auth/me:

[Feature] Add Facebook Custom Auth Support

---

.github/workflows/azuresdkdrop.yml
.github/workflows/ci.yml
src/core/constants.ts
src/msha/auth/index.ts
src/msha/auth/routes/auth-login-provider-callback.ts
src/msha/auth/routes/auth-login-provider-custom.ts

New feature: Adding Twitter/X custom auth support using Twitter's manual OAuthv2 token flow.
Some quirks of Twitter's flow:
* It is not an OIDC flow so the returned information does not encompass as much as other providers
* Different properties of client id and secret in staticwebappconfig.json schema
Chore: Updated actions/upload-artifact version since v2 is now deprecated
Twitter staticwebappconfig.json:
Twitter /.auth/me:
Regression Testing below
AAD/Entra ID /.auth/me:
Google /.auth/me:
Facebook /.auth/me:
Github /.auth/me:

[Feature] Add Twitter/X Custom Auth Support

---

src/msha/auth/index.ts

Fixes #844: The regex ignores numbers in custom auth providers. Although various documented providers have numbers in their description (e.g. auth0, aadb2c). As a consequence they will not work with the local authorization emulator.
* [Doc example for aadb2c.](https://learn.microsoft.com/en-us/azure/active-directory-b2c/configure-authentication-in-azure-static-app#31-add-an-openid-connect-identity-provider)
* [Doc example for auth0](https://auth0.com/blog/support-auth0-in-azure-static-web-apps-for-blazor-wasm/)

fix msha (#844): Regex for custom authentication providers

---

.github/workflows/azuresdkdrop.yml
.github/workflows/ci.yml
docs/www/docs/cli/swa.md
package-lock.json
package.json
src/cli/commands/login/login.ts
src/core/constants.ts
src/msha/auth/index.ts
src/msha/auth/routes/auth-login-provider-callback.ts
src/msha/auth/routes/auth-login-provider-custom.ts
src/swa.d.ts

This PR reverts all merged code since the 2.0.1 release to prepare for a critical release to update the `STATIC_SITE_CLIENT_RELEASE_METADATA_URL` constant since the old URL is being decommissioned. 
git diff between 2.0.1 and this PR: 
```
diff --git a/package-lock.json b/package-lock.json
index 61433741..91f16b23 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,12 +1,12 @@
{
"name": "@azure/static-web-apps-cli",
-  "version": "2.0.2",
+  "version": "2.0.1",
"lockfileVersion": 2,
"requires": true,
"packages": {
"": {
"name": "@azure/static-web-apps-cli",
-      "version": "2.0.2",
+      "version": "2.0.1",
"license": "MIT",
"dependencies": {
"@azure/arm-appservice": "^15.0.0",
diff --git a/package.json b/package.json
index ccc1fe80..2be1e25a 100644
--- a/package.json
+++ …
```

fix: Update SWA versions.json metadata URL & chore: Prepare 2.0.2 release

---

src/cli/commands/login/login.ts
src/swa.d.ts

Make the `subscriptions` property optional in AzureProfile since it may not exist as described in Issue #890. 
Tested by removing subscriptions in my azureProfile.json and code will no longer throw an undefined error. Then the login will fallback to another means to authenticate.

(fix #890) Fix Undefined Error with No Subs in Azure Profile

---

.github/workflows/azuresdkdrop.yml
.github/workflows/ci.yml

Fixes the maxOS-12 environment is deprecated error in this repo's testing workflows
Testing: This PR's "ci" workflow should all pass

fix: Update macos image in test workflows

---

docs/www/docs/cli/swa.md
package-lock.json
package.json
src/cli/commands/login/login.ts
src/core/constants.ts
src/msha/auth/index.ts
src/msha/auth/routes/auth-login-provider-callback.ts
src/msha/auth/routes/auth-login-provider-custom.ts
src/swa.d.ts

This PR reapplies the PRs that were reverted in order to release the high critical v2.0.2 version. The diff below shows changes that were released in v2.0.2 and various e2e testing fixes.
Ran the following diff to ensure code has been reverted properly: 
`PS C:\wagit\static-web-apps-cli> git diff e941c77890c1e2e0aaf084e9ba8a17b33c411444 >> diff.txt`
```
diff --git a/.github/workflows/azuresdkdrop.yml b/.github/workflows/azuresdkdrop.yml
index 42e0cb5e..bcf6094a 100644
--- a/.github/workflows/azuresdkdrop.yml
+++ b/.github/workflows/azuresdkdrop.yml
@@ -13,7 +13,7 @@ jobs:
runs-on: ${{ matrix.os }}
strategy:
matrix:
-        os: [macos-12, windows-latest, ubuntu-latest]
+        os: [macos-14, windows-latest, ubuntu-latest]
node-version: [18.x, 20.x]
steps:
@@ -96,7 +96,7 @@ jobs:
runs-on: …
```

chore: Reapply Pull Requests Prior to Release v2.0.2

---

.github/workflows/detection-e2e-tests.yml
src/core/func-core-tools.spec.ts

This PR fixes the unit tests for func-core-tools.spec.ts which contains new logic for a bug fix from PR #900 
Unit tests are now passing: 
e2e test in PR should also pass

fix: fix unit tests

---

package-lock.json
package.json
src/core/dataApiBuilder/dab.ts
src/core/deploy-client.ts
src/core/download-binary-helper.ts
src/core/func-core-tools.ts
src/core/utils/fetch-proxy.ts
src/msha/handlers/function.handler.ts

Fixes #924 #911 #921 
The node-fetch library does not use the machine's proxy by default so this PR creates a custom wrapper around the `fetch` method to initialize the client with a proxy agent if the `HTTP_PROXY` or `HTTPS_PROXY` environment variables exist. 
Tested by customer and internal repro, the swa manifest json is now able to be downloaded from https://aka.ms/swalocaldeploy

Feature/Bug Fix: Add fetchWithProxy Method to Enable HTTP/S Proxy with node-fetch

---

src/core/download-binary-helper.ts

Fixed an issue where `ETXTBSY` and `EBUSY` errors would occur when executing processes using `spawn` after the download process ran when `StaticSiteClient` did not exist.
In this PR, we simplified the close processing and error handling after downloading the file by using the Streams Promises API, and stabilized the download process.
I wrote the following workflow and checked the failure rate of the `swa deploy` command in the branches before and after the improvement.
```yaml
jobs:
deploy:
runs-on: windows-latest
steps:
- uses: actions/checkout@v4
- uses: actions/checkout@v4
with:
repository: shibayan/static-web-apps-cli
ref: deploy-client-download
path: static-web-apps-cli
- name: Build SWA CLI
run: |
npm install
npm run build
working-directory: ./static-web-apps-cli
- name: Deploy to …
```

fix: Refactoring the download process for `StaticSiteClient`
