src/auth/app_auth_complete/index.ts
src/auth/app_auth_login_provider/index.ts
src/auth/app_auth_logout/index.ts
src/auth/app_auth_logout_complete/index.ts
src/auth/identity_auth_login_done/index.ts
src/auth/identity_auth_login_provider_callback/index.ts
src/auth/identity_auth_logout/index.ts
src/auth/identity_auth_logout_complete/index.ts
src/auth/identity_redirect_logout/index.ts
src/cli.ts
src/dashboard.ts

This tackles issue #29 where the auth flow doesn't fully match and the login/logout redirects weren't being respected.
It's useful if you have post-login/logout logic you want to run.

Matching auth flow better

---

package.json
readme.md
src/auth/routes/identity_auth_login_provider.ts
src/cli.ts
src/runtimeHost.spec.ts
src/runtimes.spec.ts
src/utils.ts

feat: serve frontend from a folder

---

readme.md
src/cli.ts
src/proxy.ts

fix: change default port from 80 to 4280

---

src/proxy.ts

fix: proxify websocket requests

---

src/utils.ts

fix: allow spawn to run on Windows

---

package.json
readme.md
src/builder.ts
src/cli/commands/start.ts
src/cli/index.ts
src/proxy.ts
src/public/404.html
src/public/unauthorized.html
src/runtimeHost.spec.ts
src/runtimeHost.ts
src/swa.d.ts
src/utils.ts

- add npm start commands to verify the cli builds correctly
- update readme to reflect the cli new behavior
- show custom 404 page if files not found
- show custom 401 if access not authorized
- use same host for app, auth and cli (not api)
- improved typgins in swa.d.ts

chore: add few improvments

---

src/utils.ts

Remove workflow missing warning

---

src/cli/commands/start.ts
src/proxy.ts
src/utils.ts

fix: check if port before running http-server

---

src/proxy/server.ts

Fix the API proxy crashing when user is logged in

---

src/proxy/routes-engine/rules/customRoutes.spec.ts
src/proxy/routes-engine/rules/customRoutes.ts

fix: improve rewrite/redirect rule logic

---

src/core/utils.test.ts
src/core/utils.ts
src/proxy/routes-engine/rules/customRoutes.spec.ts
src/proxy/routes-engine/rules/customRoutes.ts
src/proxy/server.ts
src/swa.d.ts

fix: handle special case /* in routes.json

---

src/auth/index.ts
src/auth/routes/auth_me.ts
src/proxy/server.ts
src/public/auth.html

fix: add authenticated role when user is logged in

---

.github/labeler.yml
src/proxy/routes-engine/rules/customRoutes.spec.ts
src/proxy/routes-engine/rules/customRoutes.ts
src/swa.d.ts

fix: handle the case when statusCode is a string

---

src/auth/index.ts
src/proxy/server.ts
src/public/auth.html

invalid routes to /.auth/** should return 404

---

src/auth/index.ts
src/auth/routes/auth_logout.spec.ts
src/auth/routes/auth_logout.ts
src/auth/routes/auth_me.ts
src/swa.d.ts

fix: allow post_logout_redirect_uri to be used

---

src/cli/commands/start.ts
src/cli/index.ts
src/core/builder.ts
src/core/utils.test.ts
src/core/utils.ts
src/proxy/server.ts
src/swa.d.ts

fix: skip user config if binding to a dev server

---

package-lock.json
package.json
src/auth/index.ts
src/cli/commands/start.ts
src/cli/index.ts
src/core/runtimeHost.spec.ts
src/core/utils.test.ts
src/core/utils.ts
src/proxy/routes-engine/index.ts
src/proxy/server.ts
src/swa.d.ts

Consolidate logging information to the console

---

src/cli/commands/start.ts
src/cli/index.ts

chore: move CLI flags under swa start --help

---

readme.md
src/cli/commands/start.ts
src/cli/index.ts
src/config.ts
src/core/utils.test.ts
src/core/utils.ts
src/swa.d.ts

feat: Support running external commands on startup

---

package-lock.json
package.json
src/cli/commands/start.ts
src/core/utils.ts
src/proxy/server.ts

feat: wait for dev servers to be ready at startup

---

readme.md
src/cli/index.ts
src/public/auth.html

fix: allow editing of user ID in auth screen, small updates

---

src/proxy/server.ts

fix: force exit on SIGINT/SIGTERM

---

package-lock.json
package.json
src/cli/index.ts

- hide undocumented options (they might change or need discussion)
- add examples after start help
- add documentation link to main help
- change order of usage (all our docs put context before options)

feat: update help text

---

.gitignore
cypress/integration/authentication.js
cypress/integration/route-rules-engine.js
src/core/utils/cookie.spec.ts
src/core/utils/glob.spec.ts
src/core/utils/glob.ts
src/proxy/routes-engine/index.ts
src/proxy/routes-engine/rules/customRoutes.spec.ts
src/proxy/routes-engine/rules/customRoutes.ts
src/proxy/routes-engine/rules/globalHeaders.ts
src/proxy/routes-engine/rules/navigationFallback.ts
src/proxy/routes-engine/rules/responseOverrides.ts
src/proxy/server.ts

chore: improve rules engine logic

---

cypress/fixtures/static/staticwebapp.config.json
cypress/integration/authentication.js
cypress/integration/route-rules-engine.js
package.json

chore: add more e2e for authenticated roles

---

cypress/integration/authentication.js
readme.md
src/cli/commands/start.ts
src/cli/index.ts
src/config.ts
src/proxy/server.ts
src/swa.d.ts

refactor: rename --routes-location

---

src/proxy/server.ts

fix: avoid blocking URL ending with routes.json

---

src/auth/index.ts
src/cli/commands/start.ts

I am not sure if alias part is correct, let me know, if it needs to be changed.

add support for purging auth info

---

package-lock.json
package.json
src/proxy/server.ts

feat: warn if function app has non-http triggers

---

readme.md

I didn't quite know what was going on when I hit the auth UI, this might help improve the framing for new walk-ups.

docs: Suggested clarification text around the mock auth UI

---

src/cli/commands/start.ts

fix: display error when cli port is in use

---

cypress/integration/authentication.js
cypress/integration/authorization.js
src/msha/middlewares/request.middleware.ts

fix: force use GET method if serving static files

---

src/msha/middlewares/request.middleware.ts

fix: serve 4xx pages when using dev server

---

cypress/integration/route-rules.js
src/msha/handlers/auth.handler.ts
src/msha/middlewares/request.middleware.ts
src/msha/middlewares/response.middleware.ts
src/msha/routes-engine/route-processor.ts

fix: parse query strings when userconfig isnt used

---

.github/ISSUE_TEMPLATE/bug_report.md

docs: add port instructions in the issue template

---

src/msha/server.ts

Print notice that the emulator may not match the cloud environment

---

src/config.ts
src/core/utils/net.spec.ts
src/core/utils/net.ts
src/msha/server.ts

fix: bind to http://localhost by default

---

readme.md

Related: https://github.com/Azure/static-web-apps-cli/issues/275

docs: update readme with missing flags

---

src/core/utils/logger.ts
src/msha/routes-engine/rules/response-overrides.ts

fix: redirect property in responseOverride doesn't behave as expected

---

src/msha/routes-engine/rules/routes.spec.ts
src/msha/routes-engine/rules/routes.ts

Fix for #292. @manekinekko : Can you validate please ?

fix: File without extension return 404 #292

---

src/msha/routes-engine/route-processor.ts

fix: Appended Query params to the URL

---

src/msha/handlers/function.handler.ts

Update --api to --api-location

---

cypress/fixtures/api/host.json
cypress/fixtures/static/staticwebapp.config.json
readme.md
src/cli/commands/start.ts
src/cli/index.ts
src/core/constants.ts
src/msha/routes-engine/rules/routes.ts

fix: --app-location and --output-location not serving content from specified directories

---

cypress/fixtures/blazor-starter/swa-cli.config.json
cypress/fixtures/static/swa-cli.config.json
cypress/integration/route-rules.js
src/msha/routes-engine/route-processor.spec.ts
src/msha/routes-engine/route-processor.ts

Closes #229
Closes #375
Closes #352

fix: support query strings on static content

---

package-lock.json
package.json
src/cli/commands/start.ts
src/core/func-core-tools.ts

fix: avoid CLI crashes when func crashes

---

cypress/fixtures/blazor-starter/staticwebapp.config.json
cypress/fixtures/static/staticwebapp.config.json
cypress/integration/route-rules.js
src/core/utils/glob.spec.ts
src/core/utils/glob.ts
src/msha/routes-engine/route-processor.ts
src/msha/routes-engine/rules/navigation-fallback.ts

fix: improve glob expressions matching 

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/library-scripts/node-debian.sh
cypress/fixtures/blazor-starter/swa-cli.config.json

feat: provide complete devcontainer with support for e2e tests

---

package-lock.json
package.json
src/cli/commands/start.ts
src/core/prompts.ts
src/core/utils/net.ts
src/msha/server.ts

fix: set a random port if --port is already taken

---

docs/ENV.md
readme.md
src/cli/commands/deploy.spec.ts
src/cli/commands/deploy.ts
src/config.ts
src/core/constants.ts
src/core/deploy-client.ts
src/swa.d.ts

```
swa deploy --env production
```

feat: add support for deployment environments

---

src/cli/commands/build.ts
src/cli/index.ts
src/core/utils/command.ts
src/core/utils/index.ts

Note: this PR needs #457 to be merge first, I'll rebase it after

feat: add swa command 🪄

---

src/msha/middlewares/request.middleware.ts
src/msha/middlewares/response.middleware.ts
src/msha/routes-engine/route-processor.spec.ts
src/msha/routes-engine/route-processor.ts
src/msha/routes-engine/rules/routes.ts

fix: improve query params logic if dev server

---

docs/www/docs/use/2-emulator.md
docs/www/docs/use/3-api-server.md

Congrats on the release! 🎉
While reading the docs, I found a couple of typos.

docs: fix typos on emulator and api-server pages

---

src/msha/routes-engine/rules/routes.spec.ts

test: fix typo in routes.spec.ts

---

docs/www/docs/cli/swa-build.md
docs/www/docs/cli/swa-deploy.md
docs/www/docs/cli/swa-start.md
src/cli/commands/login.ts

docs: fix subscription example and add output-location note  

---

src/cli/commands/deploy.ts

fix: Case-insensitive checking environment value

---

docs/www/docs/contribute/99-troubleshooting.md

Add a new section in the troubleshooting about how to fix `libsecret-1.so.0` issues.

docs: add libsecret-1.so.0 troubleshooting

---

src/msha/server.ts

I**mprove the SWA CLI local dev time by ~70%!**
Related discussion: https://github.com/Azure/static-web-apps-cli/discussions/554

fix(start): keep connection open with http-proxy

---

src/core/utils/glob.spec.ts
src/core/utils/glob.ts
src/msha/routes-engine/route-processor.ts

fix(core): match * glob in routes

---

package-lock.json

chore: upgrade dependency version to fix security vulnerability

---

docs/www/docs/use/1-install.md

doc: node runtime updates

---

docs/www/docs/contribute/99-troubleshooting.md

This domain will be hit when there's a new version of function core tools

docs: added one more domain to firewall section in troubleshoot

---

docs/www/docs/use/1-install.md

@sgollapudi77 please add this small change as it is a formatting fix

docs: Formatting fix

---

docs/www/docs/contribute/99-troubleshooting.md

docs: Update troubleshooting doc to add buildId and other variable names

docs: Update troubleshooting doc

---

docs/www/docs/cli/swa.md

fix: fix the env-vars broken link

---

schema/swa-cli.config.schema.json
src/cli/commands/deploy/deploy.ts
src/cli/commands/deploy/register.ts
src/core/utils/user-config.ts
src/core/utils/workflow-config.ts
src/swa.d.ts

Data API Location can be specified via cli arg, config file parameter, workflow file parameter

Add support for custom data api location for the deploy command

---

schema/swa-cli.config.schema.json
src/cli/commands/deploy/deploy.ts
src/cli/commands/deploy/register.ts
src/core/utils/user-config.ts
src/core/utils/workflow-config.ts
src/swa.d.ts

* Added support for custom data api location for the deploy command (cli arg, config file parameter, workflow file parameter)
* Update src/cli/commands/deploy/deploy.ts
* adding logging when folder is found and error out when folder not found
* Adding dataApiLocation to deploy command parameters
---------

[Cherrypick] feat: Add support for custom data api location for the deploy command (#664)

---

docs/www/docs/contribute/99-troubleshooting.md

Docs stopped updating from sometime due to this syntax error.

fix: fix Syntaxerror while parsing docs.

---

src/cli/commands/db/init/init.spec.ts
src/cli/commands/db/init/init.ts
src/core/dataApiBuilder/dab.spec.ts
src/core/dataApiBuilder/dab.ts
src/core/utils/platform.spec.ts
src/msha/handlers/dab.handler.spec.ts
src/msha/handlers/dab.handler.ts
src/swa.d.ts

tests: add unit tests for dab-init changes

tests: add unit tests for dab-integration changes

---

package-lock.json
package.json

Reverts Azure/static-web-apps-cli#696

Revert "chore: bump into 1.1.3-alpha after release"

---

package-lock.json
package.json

Reverts Azure/static-web-apps-cli#769

Revert "chore: prep-release 1.1.5"

---

package-lock.json
package.json

Reverts Azure/static-web-apps-cli#827

Revert "chore: prep release 1.1.8"

---

.github/workflows/azuresdkdrop.yml
package-lock.json
package.json

Updating package.json and package-lock.json version number for new SWA CLI release

Update version # of CLI for Release 1.1.9

---

src/core/frameworks/frameworks.ts

(#856) fix: hugo.toml detection

---

docs/www/docs/cli/swa.md

Fix swa.md typo

---

.github/workflows/azuresdkdrop.yml
.github/workflows/ci.yml

Fixes release drop workflow error: 
Testing criteria: 
All actions in this PR should be green and working

fix: Fix package upload artifact error
